### ISSUE TITLE
run tokenize_pdb.py error

### ISSUE THREAD

**Issue by wtyang908** [instadeepai/protein-structure-tokenizer#2]
when I run tokenize_pdb.py, I met this
Traceback (most recent call last):
  File "/app/scripts/tokenize_pdb.py", line 108, in <module>
    main(
  File "/app/scripts/tokenize_pdb.py", line 64, in main
    runner.tokenize(
  File "/app/scripts/inference_runner.py", line 261, in tokenize
    graphs = [
  File "/app/scripts/inference_runner.py", line 262, in <listcomp>
    make_graph_from_pdb(
  File "/app/scripts/inference_runner.py", line 64, in make_graph_from_pdb
    protein_graph = preprocess_sample(
  File "/app/structure_tokenizer/data/preprocessing.py", line 180, in preprocess_sample
    ) = compute_nearest_neighbors_graph(
  File "/app/structure_tokenizer/utils/protein_utils.py", line 373, in compute_nearest_neighbors_graph
    means_of_atom_coordinates = np.stack(
  File "<__array_function__ internals>", line 200, in stack
  File "/opt/conda/envs/structure-tokenizer/lib/python3.10/site-packages/numpy/core/shape_base.py", line 460, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
I want to know why this is happening and how I can fix it

**Comment by JeremieDona** [comment]
Could you provide more details on how you use the `tokenize_pdb.py` ?
